### ISSUE TITLE
Any plans to add frameCount?

### ISSUE THREAD

**Issue by boothead** [parenparen/purescript-p5#1]
I've just started playing p5. Are you planning to add `frameCount` or any idea where would be the best place to add it if I was to send a PR?

**Comment by parenparen** [comment]
I have no specific plans to add `frameCount`, but it would be a good addition to the library. The code is organized according to the p5.js reference (https://p5js.org/reference/). Since `frameCount` is defined under "Environment" in the p5.js reference, it would make sense to add it to https://github.com/parenparen/purescript-p5/blob/master/src/P5/Environment.purs.

**Comment by boothead** [comment]
Cool - I'll send something over the next couple of days!

**Comment by parenparen** [comment]
Great, thanks!

**Comment by parenparen** [comment]
frameCount added with https://github.com/parenparen/purescript-p5/pull/2.
